---
title: "Philosopher Analyst"
description: |
  A technical blog by Zoë Turner
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```


This was the first blog site I set up using {distill} and I've kept this for technical posts. The pictures I use here are my own that I've taken on my rambles.

My second blog site was build using [Hugo Apéro](https://philosopher-analyst.netlify.app/) which is also called Philosopher Analyst but is published through Netlify. It is where I post less technical blogs as well as host the R training materials I use for the [NHS-R Community](https://twitter.com/NHSRCommunity) as some organisations block access to GitHub. Interestingly, others block Netlify, but not GitHub, which is why I have copied the [prework for courses](https://lextuga007.github.io/PhilosopherAnalyst/posts/2022-06-07-prework-for-courses/) on my {distill} site.

## Blogs I've contributed to

I am a Senior Fellow of the [NHS-R Community](https://twitter.com/NHSRCommunity) and have written a few [blogs](https://nhsrcommunity.com/blog/author/z-turner/) for the community and I worked for the [CDU Data Science Team](https://cdu-data-science-team.github.io/project-showcase/) in Nottinghamshire Healthcare NHS Foundation Trust until 2022 as a Data Scientist where I contributed to the [team's blog](https://cdu-data-science-team.github.io/team-blog/).


## Why Philosopher Analyst?

I studied Philosophy many years ago and had no idea about analysis or programming but I was lucky to get a chance to work with some A&E data in one job and was hooked on data from then on. I started out using SQL and my journey into learning R started around the same time as NHS-R Community started. 